name: Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-aws-cli:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar aws cli
        run: |
            sudo apt install -y awscli
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default_region_name ${{ secrets.AWS_DEFAULT_REGION_NAME }}
            aws configure set default_output_format JSON
    
      - name: Fazer deploy
        run: |
          cd lambda_functions/funcaoBasicaDeTeste
          zip lambda_functions/funcaoBasicaDeTeste/lambda_function.py funcaoBasicaDeTeste.zip
          aws lambda update-function-code --function-name funcaoBasicaDeTeste --zip-file fileb://lambda_functions/funcaoBasicaDeTeste/funcaoBasicaDeTeste.zip
